### ISSUE TITLE
Some news audios are playing more than others

### ISSUE THREAD

**Issue by RyuuzakiL5** [hellcat707hp/GTRadio#16]
**Describe the bug**
Some news audios like "the broken bridge" (news 1) are playing more than others

**To Reproduce**
I use a lot this apk when I'm driving, and what I'm noticing is that the news are not totally random. I know we had more than 60 news but "the broken bridged" news (news 1) plays 50% of the time, there are others news that play constantly too and some that never plays. Is is possible that the code is missing some news because of the quantity of digits since news audios have the same name but differ just by the numbering? 

**Expected behavior**
News should play like DJ's audio and ads that are cleary random and plays everyone at least once by a amount of time.

**Comment by hellcat707hp** [comment]
Thanks for the report @RyuuzakiL5. I'll take a look at this!

**Comment by hellcat707hp** [comment]
@RyuuzakiL5, I replicated your issue for Gen3 stations (GTA IV), and have a fix in the works. I'll reply here once the new version is available.

**Comment by hellcat707hp** [comment]
@RyuuzakiL5, this fix has been published in v1.1.2 which you can find over on the [Releases](https://github.com/hellcat707hp/GTRadio/releases) page! 

Thank you for your report and hopefully this will resolve your issue!

**Comment by RyuuzakiL5** [comment]
Thanks! Did you also saw my post on suggestions?
https://github.com/hellcat707hp/GTRadio/discussions/15

Great apk!

**Comment by hellcat707hp** [comment]
I'll take a look!
