### ISSUE TITLE
Crash on app start up after setting folder.

### ISSUE THREAD

**Issue by icuryer** [hellcat707hp/GTRadio#17]
I am having an issue with the application where it will crash on start up, I assume it may be due to me not setting up the files properly. I've been trying for hours but can't seem to get it to work. If this is the cause of the crashes would you be able to provide screenshots of what it looks like without place holder names? 

Love your work!

**Comment by hellcat707hp** [comment]
Hey, @icuryer!

It might be better for you to share what your structure looks like, because then I can tell if its folder structure or something else entirely.

I'm going to also create myself an issue to add some better logging so these errors are easier to view/report in the future.

**Comment by icuryer** [comment]
Thanks for your quick reply!! Hopefully these screenshots go through in order. I am also wondering if flac is supported? 

![Screenshot_20240622_005925_MiXplorer](https://github.com/hellcat707hp/GTRadio/assets/16075826/75be7b96-0bf6-4da2-8216-50e88e104507)
![Screenshot_20240622_005936_MiXplorer](https://github.com/hellcat707hp/GTRadio/assets/16075826/935298bc-895f-4b2b-a815-4b34dc26fec4)
![Screenshot_20240622_005943_MiXplorer](https://github.com/hellcat707hp/GTRadio/assets/16075826/7582d8ca-8d0b-492c-81ec-0f863017f1e0)
![Screenshot_20240622_005947_MiXplorer](https://github.com/hellcat707hp/GTRadio/assets/16075826/5219ae96-4d08-4bdc-8d7e-d205f9baed21)
![Screenshot_20240622_005958_MiXplorer](https://github.com/hellcat707hp/GTRadio/assets/16075826/7d478e88-d5ef-4b8a-b2f1-410414c48623)

**Comment by icuryer** [comment]
Okay so I've made those changes and it's not crashing, but now the app is on the no groups available page.

![Screenshot_20240622_012102_GTRadio](https://github.com/hellcat707hp/GTRadio/assets/16075826/20562090-351a-4b42-be78-e6052a071dba)

**Comment by hellcat707hp** [comment]
Alright, one step closer 😄

Can you close the app then find the app in Settings > Apps, clear all of its data and remove access to storage. Then relaunch the app, select the GamesFolder again, and see if it resolves? 

I'm wondering if the change in folder structure may have altered/invalidated the access it had for those folders.

**Comment by icuryer** [comment]
Unfortunately, it went back to crashing. BUT I figured out that the problem was from the individual station logos, some of the ones I had used were .svg files, when I removed those stations the ones left were .png and boom everything worked. So all good now! Thank you so much for your help! You've got a wicked project here 😀!

**Comment by hellcat707hp** [comment]
Oh wow, I missed that! Good catch! 
I can add that to the documentation that .svg files aren't supported.

Thank you! I'm honestly amazed and excited that other people are using this little project. Hope you enjoy it as much as I do!
