### ISSUE TITLE
Music Control Notification is not showing

### ISSUE THREAD

**Issue by swapsha96** [hellcat707hp/GTRadio#5]

**Comment by hellcat707hp** [comment]
Thanks for your issue!

Unfortunately, I will be closing this for the following reasons:
1. Your issue has no valuable information in it. (We just added a template for better bug reporting if you're interested.)
2. I believe this is likely a duplicate of #2 

If I'm wrong that this isn't the same thing, feel free to resubmit your issue with more information.
